global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

# Controls what resources the prometheus server scrapes 
# Since the prometheus server exposes HTTP endpoints,
# it basically scrapes itself and monitors the prometheus server health in this example. 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['172.17.0.1:9100']
